#DB
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: passwordz123
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: brianduong321@gmail.com
EMAIL_PASSWORD: eebs btwu miao ymfa
VERIFY_EMAIL_HOST: http://localhost:8085
