#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: passwordz123
POSTGRESQL_HOST: localhost:7000
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8085